import random

zobrist_piece_pos = [[[random.getrandbits(64) for _ in range(64)] for _ in range(6)] for _ in range(2)]
zobrist_castling = [random.getrandbits(64) for _ in range(16)]
zobrist_en_passant = [random.getrandbits(64) for _ in range(8)]
zobrist_black_to_move = random.getrandbits(64)


with open('zobrist.h', 'w') as f:
    f.write('#ifndef CHESSPP_ZOBRIST_H\n')
    f.write('#define CHESSPP_ZOBRIST_H\n')
    f.write('// This file is generated by zobrist.py\n\n')

    f.write('#include <cstdint>\n\n')

    f.write('struct Zobrist {\n')
    f.write('    uint64_t piece_pos[2][6][64];\n')
    f.write('    uint64_t castling_rights[16];\n')
    f.write('    uint64_t en_passant[8];\n')
    f.write('    uint64_t black_to_move;\n')
    f.write('};\n')
    f.write('extern const Zobrist zobrist;\n\n')

    f.write('#endif //CHESSPP_ZOBRIST_H\n')


with open('zobrist.cpp', 'w') as f:
    f.write('// This file is generated by zobrist.py\n')
    f.write('#include "zobrist.h"\n\n')

    f.write('const Zobrist zobrist = {\n')
    f.write('.piece_pos = {')
    for color in range(2):
        f.write('{')
        for type in range(6):
            f.write('{')
            for square in range(64):
                f.write(f'0x{zobrist_piece_pos[color][type][square]:x},')
            f.write('},')
        f.write('},')
    f.write('},')

    f.write('.castling_rights = {')
    for i in range(16):
        f.write(f'0x{zobrist_castling[i]:x},')
    f.write('},')

    f.write('.en_passant = {')
    for i in range(8):
        f.write(f'0x{zobrist_en_passant[i]:x},')
    f.write('},')

    f.write(f'.black_to_move = 0x{zobrist_black_to_move:x}')
    f.write('};\n')